FOUNDATION_REGISTRY_SEED = [
    {
        "type_id": "universe_scale.short",
        "category": "universe_scale",
        "name": "Short Story Scale",
        "description": "Small cast, one central conflict, limited locations, compact timeline.",
        "tags": ["scale", "short", "compact"],
        "compatible_with": ["movie", "short_story", "one_shot"],
        "conflicts_with": ["civilization_scale", "multi_generation_saga"],
        "risk_notes": ["Too many major characters will overload this scale."],
        "example_output": "A focused story around one protagonist, one core wound, and one decisive conflict.",
        "created_by": "system",
    },
    {
        "type_id": "universe_scale.novel_series",
        "category": "universe_scale",
        "name": "Novel Series Scale",
        "description": "Large world, multiple arcs, recurring cast, slow-burn development.",
        "tags": ["scale", "novel_series", "long_form"],
        "compatible_with": ["dark_academy", "political_fantasy", "romance", "progression"],
        "conflicts_with": ["single_scene_story"],
        "risk_notes": ["Requires strong continuity, character memory, and subplot tracking."],
        "example_output": "A seven-book saga with evolving world rules, character arcs, and faction consequences.",
        "created_by": "system",
    },
    {
        "type_id": "universe_scale.civilization",
        "category": "universe_scale",
        "name": "Civilization Simulation Scale",
        "description": "Population-level simulation with factions, resources, laws, and emergent history.",
        "tags": ["scale", "civilization", "simulation", "large_population"],
        "compatible_with": ["minecraft_civilization", "kingdom_simulation", "post_collapse"],
        "conflicts_with": ["one_room_drama"],
        "risk_notes": ["Needs strict state management or it becomes impossible to track."],
        "example_output": "A 1500-player civilization story where settlements, laws, wars, legends, and factions emerge.",
        "created_by": "system",
    },
    {
        "type_id": "engine.foundation.registry",
        "category": "engine_category",
        "name": "Type Registry Engine",
        "description": "Stores reusable creative and system types used across MythOS Engine.",
        "tags": ["foundation", "registry", "system"],
        "compatible_with": ["all_engines"],
        "conflicts_with": [],
        "risk_notes": ["Duplicate or vague type IDs will weaken long-term consistency."],
        "example_output": "destiny.kingmaker.hidden, law.class_restriction, romance.slow_burn",
        "created_by": "system",
    },
    {
        "type_id": "engine.foundation.audit",
        "category": "engine_category",
        "name": "Audit Engine",
        "description": "Records engine runs, model calls, parameters, summaries, warnings, errors, and quality scores.",
        "tags": ["foundation", "audit", "traceability"],
        "compatible_with": ["model_calls", "engine_runs", "research"],
        "conflicts_with": [],
        "risk_notes": ["Without audit records, generation cannot be debugged or evaluated properly."],
        "example_output": "An audit record for a world-generation run.",
        "created_by": "system",
    },
    {
        "type_id": "engine.foundation.versioning",
        "category": "engine_category",
        "name": "Versioning Engine",
        "description": "Stores saved states of generated objects such as worlds, characters, scenes, branches, and reports.",
        "tags": ["foundation", "versioning", "canon"],
        "compatible_with": ["canon_locking", "branching", "exports"],
        "conflicts_with": [],
        "risk_notes": ["Without versions, the user can lose strong earlier generations."],
        "example_output": "World Bible v0.1, Character Profile v0.3, Plot Outline v2.",
        "created_by": "system",
    },
    {
        "type_id": "content.profile.teen",
        "category": "content_rating",
        "name": "Teen Content Profile",
        "description": "Allows moderate conflict, emotional intensity, and romance while avoiding explicit content.",
        "tags": ["content", "rating", "teen"],
        "compatible_with": ["academy", "adventure", "romance", "fantasy"],
        "conflicts_with": ["restricted_explicit_content"],
        "risk_notes": ["Dark trauma or violence must be handled with restraint."],
        "example_output": "A dark academy story with intense rivalry and romance but no explicit content.",
        "created_by": "system",
    },
    {
        "type_id": "content.profile.dark",
        "category": "content_rating",
        "name": "Dark Content Profile",
        "description": "Allows mature emotional intensity with user-controlled boundaries.",
        "tags": ["content", "rating", "dark", "mature"],
        "compatible_with": ["thriller", "dystopian", "dark_fantasy", "political"],
        "conflicts_with": [],
        "risk_notes": ["Requires content warnings and user-defined hard limits."],
        "example_output": "A mature political fantasy with betrayal, loss, trauma, and moral collapse.",
        "created_by": "system",
    },
    {
        "type_id": "audit.engine_run",
        "category": "audit_event_type",
        "name": "Engine Run",
        "description": "An engine executed and returned a structured result.",
        "tags": ["audit", "engine", "run"],
        "compatible_with": ["all_engines"],
        "conflicts_with": [],
        "risk_notes": [],
        "example_output": "World Builder Engine generated a world-state object.",
        "created_by": "system",
    },
    {
        "type_id": "audit.model_call",
        "category": "audit_event_type",
        "name": "Model Call",
        "description": "A generation, classification, ranking, or extraction model was called.",
        "tags": ["audit", "model", "ml", "llm"],
        "compatible_with": ["ml_research", "llm_generation", "evaluation"],
        "conflicts_with": [],
        "risk_notes": ["Model calls should record provider, model name, parameters, and output summary."],
        "example_output": "LLM generated a chapter draft from a structured scene plan.",
        "created_by": "system",
    },
    {
        "type_id": "feedback.favorite_character",
        "category": "feedback_type",
        "name": "Favorite Character",
        "description": "User marked a character as especially strong, memorable, or emotionally important.",
        "tags": ["feedback", "character", "preference"],
        "compatible_with": ["character_scoring", "human_preference_model"],
        "conflicts_with": [],
        "risk_notes": ["Should be linked to a specific character ID, not just the whole project."],
        "example_output": "The user marks Kael as the strongest generated character.",
        "created_by": "system",
    },
    {
        "type_id": "feedback.boring_scene",
        "category": "feedback_type",
        "name": "Boring Scene",
        "description": "User marked a scene as weak, slow, or emotionally flat.",
        "tags": ["feedback", "scene", "quality"],
        "compatible_with": ["critic_engine", "rewrite_engine", "pacing_engine"],
        "conflicts_with": [],
        "risk_notes": ["Should trigger rewrite suggestions or pacing analysis later."],
        "example_output": "The user marks Chapter 3 Scene 2 as boring.",
        "created_by": "system",
    },
    {
        "type_id": "canon.locked",
        "category": "canon_status",
        "name": "Locked Canon",
        "description": "Protected from automatic overwrite by generation engines.",
        "tags": ["canon", "locked", "protected"],
        "compatible_with": ["versioning", "exports", "continuity"],
        "conflicts_with": ["canon.rejected"],
        "risk_notes": ["Too many locks can make generation rigid; use intentionally."],
        "example_output": "The protagonist must have exactly one younger sister.",
        "created_by": "system",
    },
    {
        "type_id": "canon.alternate",
        "category": "canon_status",
        "name": "Alternate Timeline",
        "description": "Valid inside a branch but not part of main canon.",
        "tags": ["canon", "branch", "alternate_timeline"],
        "compatible_with": ["branching", "what_if", "game_choice"],
        "conflicts_with": ["main_canon_only"],
        "risk_notes": ["Must not pollute main canon unless promoted by user.",
        ],
        "example_output": "A timeline where the villain becomes the protagonist.",
        "created_by": "system",
    },
    {
        "type_id": "export.json_state",
        "category": "export_type",
        "name": "JSON State Export",
        "description": "Machine-readable export of project or universe state.",
        "tags": ["export", "json", "state"],
        "compatible_with": ["backend", "api", "research", "backup"],
        "conflicts_with": [],
        "risk_notes": ["Should include IDs and structured state, not only prose.",
        ],
        "example_output": "exports/json/proj_abc_state.json",
        "created_by": "system",
    },
    {
        "type_id": "export.ip_bible_docx",
        "category": "export_type",
        "name": "IP Bible DOCX Export",
        "description": "Future studio-facing document export for world, characters, story, adaptation, and commercial notes.",
        "tags": ["export", "docx", "ip_bible", "studio"],
        "compatible_with": ["adaptation", "commercial", "pitch"],
        "conflicts_with": [],
        "risk_notes": ["Requires strong continuity and legal/provenance metadata before commercial use."],
        "example_output": "A polished DOCX package containing world bible, character bible, and franchise plan.",
        "created_by": "system",
    },
]
